### ISSUE TITLE
contrastive_loss issue

### ISSUE THREAD

**Issue by yesic** [yueyu1030/COSINE#1]
您好，我对contrastive_loss函数有一些疑问，一个就是输入的feat是teacher模型的outputs_pseudo[-1]，不应该是输入的是student的hidden state吗？还有agreement生成不是一个N*N的矩阵吗？

**Comment by yueyu1030** [comment]
1. We modify the function of the Roberta encoder so that outputs_pseudo[-1] will be the feature output. We empirically find teacher model's feature will lead to more stable results.  See https://github.com/yueyu1030/COSINE/blob/main/modeling_roberta.py#L88 for details.
2. To accelerate contrastive learning, we adopt the doubly stochastic sampling approximation to reduce the computational cost. Specifically, the high confidence samples $C$ in each batch $\B$ yield $O(|C|^2)$ sample pairs, and we sample $|C|$ pairs from them.

**Comment by yesic** [comment]
非常感谢你解答了我的疑惑，还有一个小问题是teacher模型的参数不是不更新的吗？那么用teacher的feat怎么影响网络的学习呢？

**Comment by yueyu1030** [comment]
The teacher model is updated periodically.  See https://github.com/yueyu1030/COSINE/blob/main/trainer.py#L158 for details.

**Comment by yesic** [comment]
Thanks a lot.

**Comment by yueyu1030** [comment]
Thanks. I am going to close this issue but feel free to contact me if you have further questions : )
